### ISSUE TITLE
Support Android Jetpack Compose

### ISSUE THREAD

**Issue by udev** [Jumio/mobile-webview#2]
See sample project: https://github.com/udev/Netverify-Fails-in-Android-Jetpack-Compose

Actual:

Loading a page from netverify.com into a native Android Webview results in a blank screen when attempting to use Android Jetpack Compose. Upon inspection using Chrome developer tools the body height and width properties for the affected pages are 100% rather than `auto`. https://css-tricks.com/almanac/properties/f/flex/#flex-0-auto

Expected:

Pages served by netverify.com use `auto` height and width allowing pages to properly render in the native Android WebView.

<img width="1792" alt="Screen Shot 2021-05-01 at 19 13 30" src="https://user-images.githubusercontent.com/409121/116900711-aa2c3980-abfe-11eb-9611-344ab433a5e9.png">
<img width="1792" alt="Screen Shot 2021-05-01 at 19 12 47" src="https://user-images.githubusercontent.com/409121/116900717-ac8e9380-abfe-11eb-9860-1094dc32baa1.png">

**Comment by BernadetteTh** [comment]
Hello @udev,
thank you for bringing this to our attention! I've forwarded the issue and we'll be looking into it. 

However, since Jetpack Compose is still in beta, it is not officially supported yet. If this is an urgent matter, please contact support@jumio.com

**Comment by udev** [comment]
Thanks @bratapfelmus. I have contacted support and will coordinate with them.
